name: 'Test action'

on:
  workflow_dispatch:   # Allow triggering pipeline manually via web UI

  push:
    branches:
      - main   # Trigger pipeline on push to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3   # Get project sources onto runner
    
      - name: Run test action
        run: |
          ls -lAh
      
      - name: Send status notification
        if: ${{ always() }}
        run: |
          if [[ ${{ job.status }} = "success" ]];
          then
            icon=":white_check_mark:"
          elif [[ ${{ job.status }} = "failure" ]];
          then
            icon=":red_circle:"
          else
            icon=":information_source:"
          fi

          msgBody="${icon} Deployment ${{ github.repository }} <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>${{ job.status }}</a>"

          postData="{ \"displayName\":\"Github Action\", \"format\":\"html\", \"text\":\"${msgBody}\" }"

          curl -s --stderr - -X POST -H "Content-Type: application/json" -d "${postData}" "${{ secrets.WEBHOOK_URL }}"
