name: 'Test action'

on:
  workflow_dispatch:   # Allow triggering pipeline manually via web UI

  push:
    branches:
      - main   # Trigger pipeline on push to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3   # Get project sources onto runner
    
      - name: Run test action
        run: |
          lsss -lAh
      
      - name: Handle failure
        if: ${{ always() }}
        run: |
          echo "${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}"

          if [[ ${{ job.status }} = "success" ]];
          then
            echo "ok"
          elif [[ ${{ job.status }} = "failure" ]];
          then
            echo "fail"
          else
            echo "${{ job.status }}"
          fi


          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
