name: 'Test action'

on:
  workflow_dispatch:   # Allow triggering pipeline manually via web UI

  push:
    branches:
      - main   # Trigger pipeline on push to this branch
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3   # Get project sources onto runner
    
      - name: Run test action
        run: |
          ls -lAh
      
      - name: Send status notification
        if: ${{ always() }}
        run: |
          if [[ ${{ job.status }} = "success" ]];
          then
            prefix="&#9989; "
            jobStatus="succeeded"
          elif [[ ${{ job.status }} = "failure" ]];
          then
            prefix="&#128308; "
            jobStatus="failed!"
          else
            prefix=""
            jobStatus="${{ job.status }}"
          fi

          msgBody="${prefix}<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Holinger CMS deployment</a> triggered by ${{ github.actor }} from branch ${{ github.ref_name }} has ${jobStatus}"
          postData="{ \"username\":\"Github Action\", \"version\":\"v2\", \"html\":\"${msgBody}\" }"

          curl -s --stderr - -X POST -H "Content-Type: application/json" -d "${postData}" "${{ secrets.HOOKSHOT_URL }}"
